### ISSUE TITLE
Moving the uncategorized posts into the proper categories 

### ISSUE THREAD

**Issue by MakeTheBrainHappy** [MakeTheBrainHappy/AnnounceDir#3]
^^

**Comment by NilsTheBest** [comment]
It's not letting me commit changes, is that normal?

**Comment by MakeTheBrainHappy** [comment]
From what I am reading in the GitHub documentation you should be able to commit changes with "collaborator status": https://help.github.com/en/articles/permission-levels-for-a-user-account-repository

**Comment by NilsTheBest** [comment]
nvm it let me commit changes now

the script didn't categorize the new topics?

**Comment by MakeTheBrainHappy** [comment]
No, it only works in limited circumstances

You also need to manually categorize here to make the changes permanent: https://github.com/MakeTheBrainHappy/AnnounceDir/blob/master/template.html
