### ISSUE TITLE
Need favicon?

### ISSUE THREAD

**Issue by NilsTheBest** [MakeTheBrainHappy/AnnounceDir#4]
It's not important, but it'd be nice!

**Comment by MakeTheBrainHappy** [comment]
I agree. Perhaps we could add a little audio microphone?

**Comment by NilsTheBest** [comment]
![favicon](https://user-images.githubusercontent.com/41824646/62425881-5feeef00-b6de-11e9-96cd-c17b9cdeb501.png)
basically this x)

**Comment by MakeTheBrainHappy** [comment]
Yes

**Comment by NilsTheBest** [comment]
![Capture du 2019-08-05 16-23-01](https://user-images.githubusercontent.com/41824646/62471620-524c6e80-b79d-11e9-8cfc-c7236b6edd77.png)
Looks good to me! Thoughts?

**Comment by VFDan** [comment]
Looks nice to me!

**Comment by MakeTheBrainHappy** [comment]
I like it
